I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 269, in script
    show placeh with twitch
Exception: Parameter 'new_widget' is not known by ATL Transform.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 269, in script
    show placeh with twitch
  File "C:\Users\Rebecca\Documents\renpy-6.99.12.4-sdk\renpy\ast.py", line 1357, in execute
    renpy.exports.with_statement(trans, paired)
  File "C:\Users\Rebecca\Documents\renpy-6.99.12.4-sdk\renpy\exports.py", line 1455, in with_statement
    return renpy.game.interface.do_with(trans, paired, clear=clear)
  File "C:\Users\Rebecca\Documents\renpy-6.99.12.4-sdk\renpy\display\core.py", line 2217, in do_with
    clear=clear)
  File "C:\Users\Rebecca\Documents\renpy-6.99.12.4-sdk\renpy\display\core.py", line 2662, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, **kwargs)
  File "C:\Users\Rebecca\Documents\renpy-6.99.12.4-sdk\renpy\display\core.py", line 3002, in interact_core
    new_widget=layers_root)
  File "C:\Users\Rebecca\Documents\renpy-6.99.12.4-sdk\renpy\atl.py", line 433, in __call__
    raise Exception('Parameter %r is not known by ATL Transform.' % k)
Exception: Parameter 'new_widget' is not known by ATL Transform.

Windows-8-6.2.9200
Ren'Py 7.1.0.882
friendsim 1.0
Thu Sep 20 16:38:06 2018
